# Generated by Django 4.0.1 on 2023-01-23 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0005_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
