# Generated by Django 4.0.1 on 2023-01-26 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posApp', '0007_salesitems_user_sales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitems',
            name='user_sales',
        ),
        migrations.AddField(
            model_name='sales',
            name='user_sales',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
