# Generated by Django 4.0.1 on 2023-01-26 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posApp', '0010_remove_salesitems_user_sales_sales_user_sales'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
